kind: Deployment
apiVersion: apps/v1
metadata:
   name: wordpress-deployment
spec:
   selector:
      matchLabels:
        app: wordpress
   template:
      metadata:
        labels:
          app: wordpress
      spec:
        containers:
          - name: wordpress-pod
            image: wordpress:latest
            env:
              - name: WORDPRESS_DB_HOST
                value: mysql-service
              - name: WORDPRESS_DB_PASSWORD
                value: hdqmdhjfdqf4q3csf436
              - name: WORDPRESS_DB_USER
                value: root
              - name: WORDPRESS_DB_NAME
                value: wordpress
            ports:
              - containerPort: 80
            volumeMounts:
              - name: data-wordpress-volume
                mountPath: /var/www/html
        volumes:
          - name: data-wordpress-volume
            nfs:
              server: "10.97.250.91" 
              path: /wordpress/
